//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Player.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Player: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Player()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player"",
    ""maps"": [
        {
            ""name"": ""main"",
            ""id"": ""e4a60449-68ee-4540-9e12-611c5468924b"",
            ""actions"": [
                {
                    ""name"": ""boxmanAddSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""c414d14d-d979-442b-8256-1d764613b75e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""boxmanStop"",
                    ""type"": ""Button"",
                    ""id"": ""20f59935-75f4-443f-813d-7812cd85513e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""rotateLeft"",
                    ""type"": ""Button"",
                    ""id"": ""bc2864cc-2b22-41d6-afde-75bdcf205fca"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""rotateRight"",
                    ""type"": ""Button"",
                    ""id"": ""7dfbf553-c6aa-4ea0-8a88-85a48da2485b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""rotateUp"",
                    ""type"": ""Button"",
                    ""id"": ""95932367-5540-41ef-b5cb-4412e86ad8b3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""rotateDown"",
                    ""type"": ""Button"",
                    ""id"": ""3c62d51b-848b-42a0-9f36-327c22251268"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""down"",
                    ""type"": ""Button"",
                    ""id"": ""65da8d7f-92d0-4c9e-9fb2-fa2349d0288c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""up"",
                    ""type"": ""Button"",
                    ""id"": ""673d17b2-2c4b-4197-86af-47a8014df27a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""right"",
                    ""type"": ""Button"",
                    ""id"": ""502aca3e-8be6-4ea0-ae5b-55e3d4e04fab"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""left"",
                    ""type"": ""Button"",
                    ""id"": ""fc1d1ceb-57aa-4d4c-a239-e940c01b20c7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""back"",
                    ""type"": ""Button"",
                    ""id"": ""3e83993c-d8ac-445c-9e0b-bf82077e6a61"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""forward"",
                    ""type"": ""Button"",
                    ""id"": ""f487bb95-bd1d-4e22-bfc7-8ae08983639f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AddSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""f7694647-4fc6-44d2-bf8f-e25c8107bb89"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""originalCam"",
                    ""type"": ""Button"",
                    ""id"": ""bf78111b-da1c-4cb9-a7e6-67e074016a9c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""cam1"",
                    ""type"": ""Button"",
                    ""id"": ""aee1812d-e7fc-4a02-a264-d644aff8bde1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""cam2"",
                    ""type"": ""Button"",
                    ""id"": ""17717f47-e290-479e-8878-e8888d553e29"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""cam3"",
                    ""type"": ""Button"",
                    ""id"": ""fa165fee-aecd-4b45-8ff3-59450244f4c8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenerateJ"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9d77e755-c836-489d-a5c9-0a4b3c8f8274"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenerateK"",
                    ""type"": ""Button"",
                    ""id"": ""2c2743c1-9d40-4374-8ffb-cfae106e621b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Firework"",
                    ""type"": ""PassThrough"",
                    ""id"": ""050e3ca5-9a84-4345-b472-d734c9d0e75b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FireworkColor"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7d5fa423-dc6c-4021-80c9-91c6e267e4e5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dda8a556-6169-463c-a801-04780c9ed9c2"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenerateJ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c992309d-b778-4f84-ab45-104265f79ebc"",
                    ""path"": ""<MidiDevice>/control000"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenerateJ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9aead686-d81c-4561-beb5-0f7349c8ef2c"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenerateK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1980cc1-dd06-4d5c-970d-14a9c8cab334"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""cam1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b07cadac-47f1-40ef-865b-4f2cf8c67c70"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""cam2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""546add68-3c8f-40d1-b033-199782dda898"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""cam3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df1ef6ac-f63b-46f4-9d27-0c63be199f60"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""cam3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df7864d3-c16a-4938-9803-0ff0594dbde7"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ce5bab5-e4d0-4de3-88f9-fabad4c034e9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c4c29bd-e50d-47c0-bed5-4356c32a6cc5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""471ae642-f347-499c-a38a-1748135ac94e"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89d3c71d-b2e1-4562-b2e3-19eaff8a616c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47e660f9-ee9b-4216-b8df-9c39d94aeb60"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d2f8930c-c117-4b3f-97e1-f28cd2ae3b99"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3fa33f98-fbda-41fa-a647-4d4f3f78c690"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3f5c159-7cf0-4d4a-9539-68853eaa3433"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rotateLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba1cb95c-a817-4fe5-9f01-d1814af11526"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rotateRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da670364-714d-410a-ad7e-88c69ce4003a"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rotateUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c61277f8-3bd9-4b29-8952-8ba0a534bafc"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rotateDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d324ead-2b95-429d-bc03-35e41d9fab78"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""originalCam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71de8ba0-0986-4e9f-a789-110f6f563365"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""boxmanAddSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""565ec690-a5cb-4111-83c7-c34c636485e3"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""boxmanStop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4071de1c-d8ef-45b2-bff5-f657d93ddbb0"",
                    ""path"": ""<MidiDevice>/control033"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Firework"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d9988bf-cfa3-43af-b8bd-c3b8c1f36431"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Firework"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c0dba3b-31f0-42a8-b59c-f95f4b8419b0"",
                    ""path"": ""<MidiDevice>/control007"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireworkColor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3b9f9d5-64aa-42de-aedb-971766d4c2a4"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireworkColor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // main
        m_main = asset.FindActionMap("main", throwIfNotFound: true);
        m_main_boxmanAddSpeed = m_main.FindAction("boxmanAddSpeed", throwIfNotFound: true);
        m_main_boxmanStop = m_main.FindAction("boxmanStop", throwIfNotFound: true);
        m_main_rotateLeft = m_main.FindAction("rotateLeft", throwIfNotFound: true);
        m_main_rotateRight = m_main.FindAction("rotateRight", throwIfNotFound: true);
        m_main_rotateUp = m_main.FindAction("rotateUp", throwIfNotFound: true);
        m_main_rotateDown = m_main.FindAction("rotateDown", throwIfNotFound: true);
        m_main_down = m_main.FindAction("down", throwIfNotFound: true);
        m_main_up = m_main.FindAction("up", throwIfNotFound: true);
        m_main_right = m_main.FindAction("right", throwIfNotFound: true);
        m_main_left = m_main.FindAction("left", throwIfNotFound: true);
        m_main_back = m_main.FindAction("back", throwIfNotFound: true);
        m_main_forward = m_main.FindAction("forward", throwIfNotFound: true);
        m_main_AddSpeed = m_main.FindAction("AddSpeed", throwIfNotFound: true);
        m_main_originalCam = m_main.FindAction("originalCam", throwIfNotFound: true);
        m_main_cam1 = m_main.FindAction("cam1", throwIfNotFound: true);
        m_main_cam2 = m_main.FindAction("cam2", throwIfNotFound: true);
        m_main_cam3 = m_main.FindAction("cam3", throwIfNotFound: true);
        m_main_GenerateJ = m_main.FindAction("GenerateJ", throwIfNotFound: true);
        m_main_GenerateK = m_main.FindAction("GenerateK", throwIfNotFound: true);
        m_main_Firework = m_main.FindAction("Firework", throwIfNotFound: true);
        m_main_FireworkColor = m_main.FindAction("FireworkColor", throwIfNotFound: true);
    }

    ~@Player()
    {
        UnityEngine.Debug.Assert(!m_main.enabled, "This will cause a leak and performance issues, Player.main.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // main
    private readonly InputActionMap m_main;
    private List<IMainActions> m_MainActionsCallbackInterfaces = new List<IMainActions>();
    private readonly InputAction m_main_boxmanAddSpeed;
    private readonly InputAction m_main_boxmanStop;
    private readonly InputAction m_main_rotateLeft;
    private readonly InputAction m_main_rotateRight;
    private readonly InputAction m_main_rotateUp;
    private readonly InputAction m_main_rotateDown;
    private readonly InputAction m_main_down;
    private readonly InputAction m_main_up;
    private readonly InputAction m_main_right;
    private readonly InputAction m_main_left;
    private readonly InputAction m_main_back;
    private readonly InputAction m_main_forward;
    private readonly InputAction m_main_AddSpeed;
    private readonly InputAction m_main_originalCam;
    private readonly InputAction m_main_cam1;
    private readonly InputAction m_main_cam2;
    private readonly InputAction m_main_cam3;
    private readonly InputAction m_main_GenerateJ;
    private readonly InputAction m_main_GenerateK;
    private readonly InputAction m_main_Firework;
    private readonly InputAction m_main_FireworkColor;
    public struct MainActions
    {
        private @Player m_Wrapper;
        public MainActions(@Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @boxmanAddSpeed => m_Wrapper.m_main_boxmanAddSpeed;
        public InputAction @boxmanStop => m_Wrapper.m_main_boxmanStop;
        public InputAction @rotateLeft => m_Wrapper.m_main_rotateLeft;
        public InputAction @rotateRight => m_Wrapper.m_main_rotateRight;
        public InputAction @rotateUp => m_Wrapper.m_main_rotateUp;
        public InputAction @rotateDown => m_Wrapper.m_main_rotateDown;
        public InputAction @down => m_Wrapper.m_main_down;
        public InputAction @up => m_Wrapper.m_main_up;
        public InputAction @right => m_Wrapper.m_main_right;
        public InputAction @left => m_Wrapper.m_main_left;
        public InputAction @back => m_Wrapper.m_main_back;
        public InputAction @forward => m_Wrapper.m_main_forward;
        public InputAction @AddSpeed => m_Wrapper.m_main_AddSpeed;
        public InputAction @originalCam => m_Wrapper.m_main_originalCam;
        public InputAction @cam1 => m_Wrapper.m_main_cam1;
        public InputAction @cam2 => m_Wrapper.m_main_cam2;
        public InputAction @cam3 => m_Wrapper.m_main_cam3;
        public InputAction @GenerateJ => m_Wrapper.m_main_GenerateJ;
        public InputAction @GenerateK => m_Wrapper.m_main_GenerateK;
        public InputAction @Firework => m_Wrapper.m_main_Firework;
        public InputAction @FireworkColor => m_Wrapper.m_main_FireworkColor;
        public InputActionMap Get() { return m_Wrapper.m_main; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainActions set) { return set.Get(); }
        public void AddCallbacks(IMainActions instance)
        {
            if (instance == null || m_Wrapper.m_MainActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainActionsCallbackInterfaces.Add(instance);
            @boxmanAddSpeed.started += instance.OnBoxmanAddSpeed;
            @boxmanAddSpeed.performed += instance.OnBoxmanAddSpeed;
            @boxmanAddSpeed.canceled += instance.OnBoxmanAddSpeed;
            @boxmanStop.started += instance.OnBoxmanStop;
            @boxmanStop.performed += instance.OnBoxmanStop;
            @boxmanStop.canceled += instance.OnBoxmanStop;
            @rotateLeft.started += instance.OnRotateLeft;
            @rotateLeft.performed += instance.OnRotateLeft;
            @rotateLeft.canceled += instance.OnRotateLeft;
            @rotateRight.started += instance.OnRotateRight;
            @rotateRight.performed += instance.OnRotateRight;
            @rotateRight.canceled += instance.OnRotateRight;
            @rotateUp.started += instance.OnRotateUp;
            @rotateUp.performed += instance.OnRotateUp;
            @rotateUp.canceled += instance.OnRotateUp;
            @rotateDown.started += instance.OnRotateDown;
            @rotateDown.performed += instance.OnRotateDown;
            @rotateDown.canceled += instance.OnRotateDown;
            @down.started += instance.OnDown;
            @down.performed += instance.OnDown;
            @down.canceled += instance.OnDown;
            @up.started += instance.OnUp;
            @up.performed += instance.OnUp;
            @up.canceled += instance.OnUp;
            @right.started += instance.OnRight;
            @right.performed += instance.OnRight;
            @right.canceled += instance.OnRight;
            @left.started += instance.OnLeft;
            @left.performed += instance.OnLeft;
            @left.canceled += instance.OnLeft;
            @back.started += instance.OnBack;
            @back.performed += instance.OnBack;
            @back.canceled += instance.OnBack;
            @forward.started += instance.OnForward;
            @forward.performed += instance.OnForward;
            @forward.canceled += instance.OnForward;
            @AddSpeed.started += instance.OnAddSpeed;
            @AddSpeed.performed += instance.OnAddSpeed;
            @AddSpeed.canceled += instance.OnAddSpeed;
            @originalCam.started += instance.OnOriginalCam;
            @originalCam.performed += instance.OnOriginalCam;
            @originalCam.canceled += instance.OnOriginalCam;
            @cam1.started += instance.OnCam1;
            @cam1.performed += instance.OnCam1;
            @cam1.canceled += instance.OnCam1;
            @cam2.started += instance.OnCam2;
            @cam2.performed += instance.OnCam2;
            @cam2.canceled += instance.OnCam2;
            @cam3.started += instance.OnCam3;
            @cam3.performed += instance.OnCam3;
            @cam3.canceled += instance.OnCam3;
            @GenerateJ.started += instance.OnGenerateJ;
            @GenerateJ.performed += instance.OnGenerateJ;
            @GenerateJ.canceled += instance.OnGenerateJ;
            @GenerateK.started += instance.OnGenerateK;
            @GenerateK.performed += instance.OnGenerateK;
            @GenerateK.canceled += instance.OnGenerateK;
            @Firework.started += instance.OnFirework;
            @Firework.performed += instance.OnFirework;
            @Firework.canceled += instance.OnFirework;
            @FireworkColor.started += instance.OnFireworkColor;
            @FireworkColor.performed += instance.OnFireworkColor;
            @FireworkColor.canceled += instance.OnFireworkColor;
        }

        private void UnregisterCallbacks(IMainActions instance)
        {
            @boxmanAddSpeed.started -= instance.OnBoxmanAddSpeed;
            @boxmanAddSpeed.performed -= instance.OnBoxmanAddSpeed;
            @boxmanAddSpeed.canceled -= instance.OnBoxmanAddSpeed;
            @boxmanStop.started -= instance.OnBoxmanStop;
            @boxmanStop.performed -= instance.OnBoxmanStop;
            @boxmanStop.canceled -= instance.OnBoxmanStop;
            @rotateLeft.started -= instance.OnRotateLeft;
            @rotateLeft.performed -= instance.OnRotateLeft;
            @rotateLeft.canceled -= instance.OnRotateLeft;
            @rotateRight.started -= instance.OnRotateRight;
            @rotateRight.performed -= instance.OnRotateRight;
            @rotateRight.canceled -= instance.OnRotateRight;
            @rotateUp.started -= instance.OnRotateUp;
            @rotateUp.performed -= instance.OnRotateUp;
            @rotateUp.canceled -= instance.OnRotateUp;
            @rotateDown.started -= instance.OnRotateDown;
            @rotateDown.performed -= instance.OnRotateDown;
            @rotateDown.canceled -= instance.OnRotateDown;
            @down.started -= instance.OnDown;
            @down.performed -= instance.OnDown;
            @down.canceled -= instance.OnDown;
            @up.started -= instance.OnUp;
            @up.performed -= instance.OnUp;
            @up.canceled -= instance.OnUp;
            @right.started -= instance.OnRight;
            @right.performed -= instance.OnRight;
            @right.canceled -= instance.OnRight;
            @left.started -= instance.OnLeft;
            @left.performed -= instance.OnLeft;
            @left.canceled -= instance.OnLeft;
            @back.started -= instance.OnBack;
            @back.performed -= instance.OnBack;
            @back.canceled -= instance.OnBack;
            @forward.started -= instance.OnForward;
            @forward.performed -= instance.OnForward;
            @forward.canceled -= instance.OnForward;
            @AddSpeed.started -= instance.OnAddSpeed;
            @AddSpeed.performed -= instance.OnAddSpeed;
            @AddSpeed.canceled -= instance.OnAddSpeed;
            @originalCam.started -= instance.OnOriginalCam;
            @originalCam.performed -= instance.OnOriginalCam;
            @originalCam.canceled -= instance.OnOriginalCam;
            @cam1.started -= instance.OnCam1;
            @cam1.performed -= instance.OnCam1;
            @cam1.canceled -= instance.OnCam1;
            @cam2.started -= instance.OnCam2;
            @cam2.performed -= instance.OnCam2;
            @cam2.canceled -= instance.OnCam2;
            @cam3.started -= instance.OnCam3;
            @cam3.performed -= instance.OnCam3;
            @cam3.canceled -= instance.OnCam3;
            @GenerateJ.started -= instance.OnGenerateJ;
            @GenerateJ.performed -= instance.OnGenerateJ;
            @GenerateJ.canceled -= instance.OnGenerateJ;
            @GenerateK.started -= instance.OnGenerateK;
            @GenerateK.performed -= instance.OnGenerateK;
            @GenerateK.canceled -= instance.OnGenerateK;
            @Firework.started -= instance.OnFirework;
            @Firework.performed -= instance.OnFirework;
            @Firework.canceled -= instance.OnFirework;
            @FireworkColor.started -= instance.OnFireworkColor;
            @FireworkColor.performed -= instance.OnFireworkColor;
            @FireworkColor.canceled -= instance.OnFireworkColor;
        }

        public void RemoveCallbacks(IMainActions instance)
        {
            if (m_Wrapper.m_MainActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainActions instance)
        {
            foreach (var item in m_Wrapper.m_MainActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainActions @main => new MainActions(this);
    public interface IMainActions
    {
        void OnBoxmanAddSpeed(InputAction.CallbackContext context);
        void OnBoxmanStop(InputAction.CallbackContext context);
        void OnRotateLeft(InputAction.CallbackContext context);
        void OnRotateRight(InputAction.CallbackContext context);
        void OnRotateUp(InputAction.CallbackContext context);
        void OnRotateDown(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnUp(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
        void OnForward(InputAction.CallbackContext context);
        void OnAddSpeed(InputAction.CallbackContext context);
        void OnOriginalCam(InputAction.CallbackContext context);
        void OnCam1(InputAction.CallbackContext context);
        void OnCam2(InputAction.CallbackContext context);
        void OnCam3(InputAction.CallbackContext context);
        void OnGenerateJ(InputAction.CallbackContext context);
        void OnGenerateK(InputAction.CallbackContext context);
        void OnFirework(InputAction.CallbackContext context);
        void OnFireworkColor(InputAction.CallbackContext context);
    }
}
